CREATE TABLE IF NOT EXISTS bases (
    id SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL,
    ProductID INTEGER NOT NULL,
    Amount INTEGER NOT NULL,
    TotalCost INTEGER NOT NULL,
    Canceled BOOLEAN NOT NULL,
    BaseId INTEGER NOT NULL
);
